"""empty message

Revision ID: 766752a6fb83
Revises: d1e16d6b8306
Create Date: 2024-04-03 16:00:09.577596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766752a6fb83'
down_revision = 'd1e16d6b8306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.drop_column('texto')

    # ### end Alembic commands ###
